### ISSUE TITLE
deleteSession issue

### ISSUE THREAD

**Issue by ralfbecher** [braathen/qlik-auth#2]
Even using init() and the global object with targetId etc. the deleteSession method doesn’t work:
No matching endpoint found

**Comment by braathen** [comment]
Hi Ralf, the whole session part is not really finished or properly tested, and not really documented either to be honest.. :) It was something that was started and then other things came in between... I have lately done some work to qlik-auth not yet commited (coming up soon), but the session part still need some more love for sure... thx for reminding me! I think the session api is a underrated integration possibility, but it can be a bit more complicated to set up than ticketing...

**Comment by ralfbecher** [comment]
Hi Rikard,
thanks for your reply. I'm just looking for a simple logout when using ticketing. But nothing works..
