### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by pevans87** [braathen/qlik-auth#3]
Hiya, 

I'm sure this is a stupid question - but I'm trying to get this setup and using your starter code I'm not really having any luck - I just get a message missing parameters. 

Can you give me a bit more info on how to customise this to connect to my instance of Qlik? 

Thanks!

**Comment by braathen** [comment]
Hi,

You need to configure a virtual proxy in QMC, as custom authentication URL you give the URL to where your ticket code is running. Then you can just enter the url/<prefix>/hub or url/<prefix>/qmc  and the user will be redirected to the ticket code. The prefix is the prefix you assign to the virtual proxy. The redirection will contain the "missing parameters", which is options.targetId and options.proxyRestUri. the idea is to simplify and minimise the code needed to get it to work, but also to provide a better "flow". It also takes all kind of hard-coding away and the same code can be used for multiple instances.

**Comment by zuruprem** [comment]
Hi Braathen,

Thanks for qlik-auth. In the past used it very well for ticketing in Qlik Sense with node. Recently I changed default Qlik Sense port from 80 to 81 then logging into node proxy is generating following error
![image](https://cloud.githubusercontent.com/assets/25402337/24576774/e82c57b0-16ca-11e7-94f9-11301bbf8eb9.png)

**Comment by braathen** [comment]
Are you sure the port was the only thing you changed? if setup as a virtual proxy and custom authentication module with redirects the module should not care where it came from or where to redirect back as those values would be provided as parameters from Qlik Sense.

Please also check that you have set origin white list properly and that the user has a license allocated, and that there are licenses available and automatically assigned through license access rules.

**Comment by zuruprem** [comment]
Dear braathen,

You are correct. Providing the whitelist for new virtual proxy has resolved the issue

**Comment by braathen** [comment]
Great!
