### ISSUE TITLE
How to get the ticket?

### ISSUE THREAD

**Issue by gabiQlik** [braathen/qlik-auth#4]
I'm trying to build a webapp that includes some QS objects.
I'm able to access the QMC and HUB, by using serve-name/prefix., but I don't know how to read the received ticket to redirect the user to my custom mashup.

Could you give me some pointers?
Thank in advance.

**Comment by dedpnd** [comment]
@gabiQlik, Hi!
Look [here](http://webofwork.com/authenticate-qlik-sense-in-an-nodejs-express-app-on-an-external-web-host/)
