### ISSUE TITLE
Update npm with latest version

### ISSUE THREAD

**Issue by ghost** [braathen/qlik-auth#7]
Would it be possible to update npmjs with latest version of this module?

**Comment by vbakke** [comment]
While we wait for braathen to transfer the package to npm:
Do you know that you can also write:
   npm install braathen/qlik-auth -save

Then you download directly from GitHub. :)

(Not sure how it behaves when it comes to new updates, branches or check-ins. But at leat you get the latest code.

**Comment by ghost** [comment]
Great, I was not aware of this. Thank you :)

**Comment by vbakke** [comment]
Neither was I, until yesterday. I was tipped off by a colleague of mine, when I was complaining about the same. :)

**Comment by braathen** [comment]
I like the knowledge sharing this thread is coming to... :) awesome workaround which I wasn't aware of either. Thanks!

Sorry for my laziness regarding the npm repos. Not sure if there has been that many updates either, but maybe it's not the very latest. I lost my dev environment where I had everything set up and just hasn't had the time to look into it... maybe one day... :)
